from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(30, 150, 601, 431))
        self.label_main.setStyleSheet("border: 4px solid black")
        self.label_main.setText("")
        self.label_main.setObjectName("label_main")
        self.text_header = QtWidgets.QLabel(self.centralwidget)
        self.text_header.setGeometry(QtCore.QRect(230, 10, 621, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_header.setFont(font)
        self.text_header.setStyleSheet("border: 6px solid yellow")
        self.text_header.setObjectName("text_header")
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_plate = QtWidgets.QLabel(self.centralwidget)
        self.label_plate.setGeometry(QtCore.QRect(720, 150, 301, 181))
        self.label_plate.setStyleSheet("border: 4px solid black")
        self.label_plate.setFont(font)
        self.label_plate.setText("")
        self.label_plate.setObjectName("label_plate")
        self.button_take = QtWidgets.QPushButton(self.centralwidget)
        self.button_take.setGeometry(QtCore.QRect(810, 490, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_take.setFont(font)
        self.button_take.setObjectName("button_take")
        self.label_digits = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_digits.setGeometry(QtCore.QRect(750, 350, 251, 81))
        self.label_digits.setStyleSheet("border: 4px solid black")
        self.label_digits.setFont(font)
        self.label_digits.setText("")
        self.label_digits.setObjectName("label_digits")
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        self.button_next.setGeometry(QtCore.QRect(810, 550, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_next.setFont(font)
        self.button_next.setObjectName("button_next")
        self.text_header_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_header_2.setGeometry(QtCore.QRect(20, 750, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_header_2.setFont(font)
        self.text_header_2.setStyleSheet("border: 2px solid green")
        self.text_header_2.setObjectName("text_header_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_header.setText(_translate("MainWindow", "Hệ thống nhận diện biển số trạm thu vé"))
        self.button_take.setText(_translate("MainWindow", "Chụp"))
        self.button_next.setText(_translate("MainWindow", "Tiếp tục"))
        self.text_header_2.setText(_translate("MainWindow", "Lê Việt Anh"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())